import Link from 'next/link';
import { ConnectButton } from '@rainbow-me/rainbowkit';
import { useRouter } from 'next/router';

import { Tooltip } from '../ui/Tooltip';
import { TOOLTIPS } from '../../utils/tooltipConstants';

export function Header() {
  const router = useRouter();
  const activePath = router.pathname;

  const navItems = [
    { label: 'Ecosystem Radar', href: '/ecosystem', tooltip: TOOLTIPS.TVL },
    { label: 'Alpha Signals', href: '/opportunities', tooltip: TOOLTIPS.ALPHA_SIGNALS },
    { label: 'AI Insights', href: '/insights', tooltip: "AI Insights provide human-readable advice generated by analyzing current market data with Large Language Models." },
  ];

  return (
    <header className="mb-12 flex flex-col xl:flex-row xl:items-start justify-between gap-8 relative z-20 animate-slide-up">
      {/* Left: Title Block */}
      <div className="flex flex-col gap-4 max-w-2xl">
        <div className="inline-flex items-center gap-2.5 self-start px-3 py-1.5 rounded-full border border-accent-cyan/20 bg-accent-cyan/5 backdrop-blur-md">
          <span className="w-2 h-2 rounded-full bg-accent-cyan animate-pulse shadow-[0_0_8px_rgba(6,182,212,0.8)]" />
          <span className="text-[10px] font-black uppercase tracking-[0.2em] text-cyan-200">System Live</span>
        </div>
        
        <div>
          <Link href="/">
            <h1 className="text-5xl md:text-7xl font-black tracking-tighter text-white leading-[0.9] mb-4 hover:text-accent-cyan transition-colors cursor-pointer">
              Mantle <span className="text-accent-cyan">Atlas</span>
            </h1>
          </Link>
          <p className="text-lg md:text-xl text-slate-400 font-medium leading-relaxed border-l-2 border-accent-cyan/30 pl-5">
            The intelligent capital allocation layer for the Mantle Ecosystem.
          </p>
        </div>
      </div>

      {/* Right: Action Block */}
      <div className="flex flex-col items-end gap-6">
        <nav className="flex items-center p-1.5 bg-white/[0.03] border border-white/5 rounded-2xl backdrop-blur-md shadow-2xl">
          {navItems.map((item) => {
            const isActive = activePath === item.href;
            const content = (
              <Link
                key={item.href}
                href={item.href}
                className={`px-5 py-2.5 rounded-xl text-xs font-black uppercase tracking-wider transition-all duration-300 ${
                  isActive
                    ? 'bg-accent-cyan text-dark-950 shadow-[0_0_20px_rgba(6,182,212,0.3)]'
                    : 'text-slate-400 hover:text-white hover:bg-white/5'
                }`}
              >
                {item.label}
              </Link>
            );

            return item.tooltip ? (
              <Tooltip key={item.href} content={item.tooltip}>
                {content}
              </Tooltip>
            ) : content;
          })}
        </nav>
        
        <div className="flex items-center gap-4 animate-scale-in" style={{ animationDelay: '200ms' }}>
          <ConnectButton />
        </div>
      </div>
    </header>
  );
}
